# Generated by Django 4.1 on 2022-08-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_cabañaoferta_remove_cabaña_oferta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CabañaOferta',
        ),
    ]
