# Generated by Django 4.1 on 2022-08-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_delete_cabañaoferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos', verbose_name='Foto de Perfil')),
                ('comentario', models.TextField(null=True, verbose_name='Comentario')),
                ('archivo2', models.FileField(blank=True, null=True, upload_to='archivos2', verbose_name='Foto de experiencia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-created'],
            },
        ),
    ]
