# Generated by Django 4.1 on 2022-08-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_rename_archivo2_archivos_archivoexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabaña',
            name='EnOferta',
            field=models.CharField(default='No', max_length=50, verbose_name='¿En oferta?'),
        ),
    ]
